from fastapi.responses import PlainTextResponse
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest

HTTP_REQUEST_COUNTER = Counter(
    "fraud_platform_http_requests_total",
    "Count of HTTP requests received by service",
    ["service", "method", "path", "status_code"],
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "fraud_platform_http_request_duration_seconds",
    "Duration of HTTP requests",
    ["service", "method", "path"],
)

PRODUCER_EVENTS_COUNTER = Counter(
    "fraud_platform_producer_events_total",
    "Synthetic transactions generated by the producer",
    ["scenario", "label"],
)

WORKER_EVENTS_COUNTER = Counter(
    "fraud_platform_worker_events_total",
    "Events processed by the stream worker",
    ["stage", "status"],
)

WORKER_LATENCY_SECONDS = Histogram(
    "fraud_platform_worker_stage_latency_seconds",
    "Latency for processing worker stages",
    ["stage"],
)

REDIS_OPERATION_LATENCY_SECONDS = Histogram(
    "fraud_platform_redis_operation_latency_seconds",
    "Latency for Redis operations",
    ["operation"],
)

MODEL_PREDICTION_COUNTER = Counter(
    "fraud_platform_model_predictions_total",
    "Predictions generated by model runtime",
    ["decision", "model_alias"],
)

MODEL_RUNTIME_LATENCY_SECONDS = Histogram(
    "fraud_platform_model_runtime_latency_seconds",
    "Latency for model runtime scoring",
)

MODEL_INFO_GAUGE = Gauge(
    "fraud_platform_model_info",
    "Current model metadata and thresholds",
    ["model_name", "model_version", "model_alias"],
)

DRIFT_SCORE_GAUGE = Gauge(
    "fraud_platform_drift_score",
    "Latest drift scores emitted by trainer",
    ["metric"],
)

DLQ_COUNTER = Counter(
    "fraud_platform_dlq_events_total",
    "Count of events written to dead letter queue",
    ["failed_stage"],
)


def render_metrics() -> PlainTextResponse:
    return PlainTextResponse(generate_latest(), media_type=CONTENT_TYPE_LATEST)
