import Link from "next/link";

import { ConsoleShell } from "@/components/console-shell";
import { EmptyState } from "@/components/empty-state";
import { DecisionBadge } from "@/components/status";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { fetchJson } from "@/lib/api";

type CasesPayload = {
  items: Array<{
    case_id: string;
    transaction_id: string;
    decision: string;
    status: string;
    decision_time: string;
    score: number | null;
    scenario: string | null;
    amount: number | null;
    country: string | null;
    channel: string | null;
    account_id: string | null;
  }>;
  pagination: {
    page: number;
    page_size: number;
    total: number;
    total_pages: number;
  };
};

export default async function CasesPage({
  searchParams,
}: {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = (await searchParams) ?? {};
  const page = typeof params.page === "string" ? params.page : "1";
  const status = typeof params.status === "string" ? params.status : "";
  const decision = typeof params.decision === "string" ? params.decision : "";
  const search = typeof params.search === "string" ? params.search : "";
  const sortOrder = typeof params.sort_order === "string" ? params.sort_order : "desc";

  const query = new URLSearchParams({
    page,
    page_size: "20",
    sort_by: "decision_time",
    sort_order: sortOrder,
  });
  if (status) query.set("status", status);
  if (decision) query.set("decision", decision);
  if (search) query.set("search", search);

  const cases = await fetchJson<CasesPayload>(`/cases?${query.toString()}`);

  return (
    <ConsoleShell
      section="cases"
      title="Analyst review queue"
      subtitle="Search, filter, and inspect persisted fraud decisions generated by the streaming worker and exposed through the case API."
    >
      <Card>
        <CardHeader>
          <CardTitle>Queue Controls</CardTitle>
          <CardDescription>These filters map directly to the backend case list query.</CardDescription>
        </CardHeader>
        <CardContent>
          <form className="grid gap-4 lg:grid-cols-[1.2fr,0.7fr,0.7fr,0.7fr,auto]">
            <label className="space-y-2 text-sm">
              <span className="text-muted">Search transaction</span>
              <input
                name="search"
                defaultValue={search}
                className="w-full rounded-2xl border border-border bg-panelMuted/40 px-4 py-3 text-sm outline-none ring-0 transition focus:border-accent/40"
                placeholder="txn_00000042"
              />
            </label>
            <label className="space-y-2 text-sm">
              <span className="text-muted">Status</span>
              <select
                name="status"
                defaultValue={status}
                className="w-full rounded-2xl border border-border bg-panelMuted/40 px-4 py-3 text-sm outline-none transition focus:border-accent/40"
              >
                <option value="">All</option>
                <option value="open">Open</option>
                <option value="closed">Closed</option>
              </select>
            </label>
            <label className="space-y-2 text-sm">
              <span className="text-muted">Decision</span>
              <select
                name="decision"
                defaultValue={decision}
                className="w-full rounded-2xl border border-border bg-panelMuted/40 px-4 py-3 text-sm outline-none transition focus:border-accent/40"
              >
                <option value="">All</option>
                <option value="APPROVE">Approve</option>
                <option value="REVIEW">Review</option>
                <option value="BLOCK">Block</option>
              </select>
            </label>
            <label className="space-y-2 text-sm">
              <span className="text-muted">Sort order</span>
              <select
                name="sort_order"
                defaultValue={sortOrder}
                className="w-full rounded-2xl border border-border bg-panelMuted/40 px-4 py-3 text-sm outline-none transition focus:border-accent/40"
              >
                <option value="desc">Newest first</option>
                <option value="asc">Oldest first</option>
              </select>
            </label>
            <div className="flex items-end">
              <button className="rounded-2xl bg-accent px-5 py-3 text-sm font-medium text-background transition hover:bg-accent/90">
                Apply
              </button>
            </div>
          </form>
        </CardContent>
      </Card>

      {cases.error || !cases.data ? (
        <EmptyState
          title="Queue is unavailable"
          description={cases.error ?? "The cases API returned no data."}
        />
      ) : cases.data.items.length === 0 ? (
        <EmptyState
          title="No cases yet"
          description="The system is live, but no fraud decisions have been persisted for the selected filters."
        />
      ) : (
        <Card>
          <CardHeader>
            <CardTitle>Live case queue</CardTitle>
            <CardDescription>
              {cases.data.pagination.total} total cases across {cases.data.pagination.total_pages} page(s).
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {cases.data.items.map((item) => (
              <Link
                key={item.case_id}
                href={`/cases/${item.case_id}`}
                className="grid gap-4 rounded-2xl border border-border/70 bg-panelMuted/40 p-4 transition hover:border-accent/30 hover:bg-accent/5 md:grid-cols-[1.1fr,0.7fr,0.8fr,0.9fr,0.8fr,0.8fr]"
              >
                <div>
                  <p className="font-mono text-xs uppercase tracking-[0.24em] text-muted">{item.transaction_id}</p>
                  <p className="mt-2 text-base font-medium">{item.account_id ?? "unknown account"}</p>
                  <p className="text-sm text-muted">{item.scenario ?? "unknown scenario"}</p>
                </div>
                <Stat label="Decision" value={<DecisionBadge decision={item.decision} />} />
                <Stat label="Score" value={item.score === null ? "n/a" : item.score.toFixed(3)} />
                <Stat label="Amount" value={item.amount === null ? "n/a" : item.amount.toFixed(2)} />
                <Stat label="Geo" value={item.country ?? "n/a"} />
                <Stat label="Channel" value={item.channel ?? "n/a"} />
              </Link>
            ))}

            <div className="flex items-center justify-between border-t border-border/70 pt-4 text-sm text-muted">
              <p>
                Page {cases.data.pagination.page} of {cases.data.pagination.total_pages}
              </p>
              <div className="flex gap-3">
                {cases.data.pagination.page > 1 ? (
                  <Link
                    className="rounded-xl border border-border px-3 py-2 hover:bg-panelMuted/50"
                    href={`?${buildPageQuery(params, cases.data.pagination.page - 1)}`}
                  >
                    Previous
                  </Link>
                ) : null}
                {cases.data.pagination.page < cases.data.pagination.total_pages ? (
                  <Link
                    className="rounded-xl border border-border px-3 py-2 hover:bg-panelMuted/50"
                    href={`?${buildPageQuery(params, cases.data.pagination.page + 1)}`}
                  >
                    Next
                  </Link>
                ) : null}
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </ConsoleShell>
  );
}

function Stat({
  label,
  value,
}: {
  label: string;
  value: React.ReactNode;
}) {
  return (
    <div className="space-y-2">
      <p className="text-xs uppercase tracking-[0.24em] text-muted">{label}</p>
      <div className="text-sm font-medium">{value}</div>
    </div>
  );
}

function buildPageQuery(
  params: Record<string, string | string[] | undefined>,
  page: number,
) {
  const query = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string" && value) {
      query.set(key, value);
    }
  }
  query.set("page", page.toString());
  return query.toString();
}
