global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: producer
    metrics_path: /metrics
    static_configs:
      - targets: ["producer:8001"]

  - job_name: stream-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["stream-worker:8002"]

  - job_name: trainer
    metrics_path: /metrics
    static_configs:
      - targets: ["trainer:8003"]
